<?php
	
	/* Session Variables */
	$startDate = 1;
	$endDate = 4;
	$stdUSN = "2sd12cs133";
	/* ***************** */
	
	$con = mysql_connect("localhost","Admin","pkvcobas132");
	if(!$con)
		die("Reason : ".mysql_error());
               
	mysql_select_db("spas",$con);
	
	$totalSessionsStd = 1;
	require_once 'Classes/PHPExcel.php';
	$objPHPExcel = new PHPExcel(); 

	$arr = array();
	
	$objPHPExcel->setActiveSheetIndex(0);
	for($i = 0; $i < 5; $i++)
		for($j = 0; $j < 11; $j++)
			$arr[$i][$j] = "";
			
	$arr[0][0] = "usn";
	$arr[0][1] = "Consultation_Frequency";
	$arr[0][2] = "No_Of_Absents";
	$arr[0][3] = "Quiz_Marks";
	$arr[0][4] = "Points";
	$arr[0][5] = "Negative_Points";
	$arr[0][6] = "day1";
	$arr[0][7] = "day2";
	$arr[0][8] = "day3";
	$arr[0][9] = "day4";
	$arr[0][10] = "day5";
	
	$arr[1][0] = "2sd12cs050";
	$arr[2][0] = "2sd12cs068";
	$arr[3][0] = "2sd12cs127";
	$arr[4][0] = "2sd12cs133";
	
	$sql = "SELECT * FROM activity WHERE usn = '$stdUSN'";
	$data = mysql_query($sql,$con);
	
	//$res = mysql_fetch_array($data))
	for($j = 1; $arr[$j][0] == $stdUSN; $j++);
	for($i = $startDate+5; $i <= $endDate+5; $i++) {
		$res = mysql_fetch_array($data);
		$var = $res['seed'];
		$var = rand(3,$var);
		while($var > 0) {
			$dummy = genDay($res['seed']);
			/* Write code to Insert $dummy into DB */
			/* One day's activity of stdUSN will be generated by genDay() */
			$var--;
		}
	}
	
	for($i=0, $column='A', $rowCount = 1; $i < 5; $i++, $rowCount++) {
		for($j = 0; $j < 11; $j++,$column++) {
			$objPHPExcel->getActiveSheet()->setCellValue($column.$rowCount, $arr[$i][$j]);
		}
		$column='A';
	}	 

	$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5'); 
	$objWriter->save('C:\xampp\htdocs\SPAS\pages\RScripts\Book3.xls');
	
	function genDay($seed) {
		GLOBAL $totalSessionsStd;
		
		/*<S1;D;A;5>,<S1;R;A;2>*/
		$var = intval($seed / 10);
		echo 'Seed : '.$seed.'<br />';
		echo 'Total sessions : '.$var.'<br />';
		
		while($var > 0) {
			$a = genSess($seed); /* Generates activity for one session */
			$var--;
			$totalSessionsStd++;
		}
	}
	
	function genSess($seed) {
		GLOBAL $totalSessionsStd;
		
		$var = $seed % 10;
		echo 'Total activities in each session : '.$var.'<br />';
		
		while($var > 0) {
			$a = gen();
			//echo 'a : '.$a.'<br />';
			$var--;
		}
	}
	
	function gen() {
		GLOBAL $totalSessionsStd;
		$std = "<";
		$std = $std.' S';
		$std = $std.$totalSessionsStd;
		$var = genDVR();
		$std = $std.$var;
		$std = $std.'A';
		$var = rand(3,10);
		$std = $std.$var.'>';
		return $std;
	}
	
	function genDVR() {
		$arr = array(3);
		$arr[0] = "D";
		$arr[1] = "V";
		$arr[2] = "R";
		
		return ($arr[rand(0,2)]);
	}

?>