<?php

	/* Session Variables */
	$totalDaysSinceBenOfSem = 4;
	/* ***************** */
	
	$con = $_SESSION['con'];
	
	/*$con = mysql_connect("localhost","Admin","pkvcobas132");
	if(!$con)
		die("Reason : ".mysql_error());
               
	mysql_select_db("SPAS",$con);*/
	
	$eleName = 1;
	
	$i = 0;
	
	if(isset($_POST["submit"])) {
		$stdUSN = $_POST["hid"];
		echo $stdUSN.'<br />';
		
		$sql = "SELECT * FROM activity WHERE usn = '$stdUSN' and act != ''";
		$mydata = mysql_query($sql,$con);
		
		$daySeed = array();
		$days = array();
		$seedArr = array();
		
		$i = 0;
		while($res = mysql_fetch_array($mydata)) {
			//echo 'Days Inrc<br />';
			$daySeed[$i++] = $res['seed'];
		}
		
		$totalDaysSinceBenOfSem = $i;
		
		$i = 0;
		$j = 0;
		$seedChangeCounter = 0;
		
		echo '$totalDaysSinceBenOfSem : '.$totalDaysSinceBenOfSem.'<br />';
		
		$query = "SELECT totalsess FROM studentsess WHERE usn = '$stdUSN'";
		$mydata = mysql_query($query,$con);
		$res = mysql_fetch_array($mydata);
		$sess = $res['totalsess'];
		$sess2 = intval($sess / 10);
		echo '$sess2 : '.$sess2.'<br />';
				
		$sess = $sess - $sess2;
		echo '$sess : '.$sess.'<br />';
		
		while($i < $totalDaysSinceBenOfSem) {
			
			$var = $_POST["$eleName"];
			if( ($var % 10) == 0)
				$var++;
				
			echo '$var : '.$var.'<br />';
			echo '$daySeed[$i] : '.$daySeed[$i].'<br />';
				
			if($var != $daySeed[$i]) {
				$query = "UPDATE studentsess set totalsess='$sess' WHERE usn = '$stdUSN'";
				mysql_query($query,$con);
				
				$query = "UPDATE activity set seed='$var' WHERE usn='$stdUSN' and day='$eleName'";
			
				if(mysql_query($query,$con)) {
					echo'Successfull<br />';
				}
				else {
					echo 'Unsuccessfull<br />';
				}
				$day[$j] = $i+1;
				$seedArr[$j++] = $var;
				$seedChangeCounter++;
			}
			
			$i++;
			$eleName++;
		}
	}

	$totalSessionsStd = $sess;
	echo '$totalSessionsStd : '.$totalSessionsStd.'<br />';

	$sql = "SELECT * FROM activity WHERE usn = '$stdUSN'";
	$data = mysql_query($sql,$con);

	for($j = 0; $j < $seedChangeCounter; $j++) {
		$dummy = genDay($seedArr[$j]);
		/* Write code to Insert $dummy into DB */
		/* One day's activity of stdUSN will be generated by genDay() */
		$h = $day[$j];
		$query = "UPDATE activity SET act = '$dummy' WHERE usn = '$stdUSN' and day = '$h'";
		if(mysql_query($query,$con))
			echo 'Successfull 2<br />';
		else
			echo 'Un - Successfull 2<br />';
	}
	
	echo 'Final totalSessionsStd : '.$totalSessionsStd.'<br />';
	$query = "UPDATE studentsess set totalsess = '$totalSessionsStd' WHERE usn = '$stdUSN'";
	mysql_query($query,$con);
	
	header('Location: studentSeed.php');
	
	function genDay($seed) {
		GLOBAL $totalSessionsStd;
		
		$var = intval($seed / 10);
		if($var == 1)
			$var = 2;
		
		$a = "";
		$count = 0;
		while($var > 0) {
			$b = genSess($seed); /* Generates activity for one session */
			if( (($var != 1) || ($count != 0) ) && ($a != "") )
				$a = $a.';';
			$a = $a.$b;
			$var--;
			$totalSessionsStd++;
			$count++;;
		}
		
		return $a;
	}
	
	function genSess($seed) {
		GLOBAL $totalSessionsStd;
		
		$var = $seed % 10;
		$var = rand($var--,$var++);
		
		$a = "";
		$count = 0;
		while($var > 0) {
			$b = gen();
			if( (($var != 1) || ($count != 0) ) && ($a != "") )
				$a = $a.';';
			$a = $a.$b;
			$var--;
			$count++;
		}
		
		return $a;
	}
	
	function gen() {
		GLOBAL $totalSessionsStd;
		$std = "<";
		$std = $std.' S';
		$std = $std.$totalSessionsStd.';';
		$var = genDVR();
		$std = $std.$var.';';
		$std = $std.'A'.';';
		$var = rand(3,10);
		$std = $std.$var.'>';
		return $std;
	}
	
	function genDVR() {
		$arr = array(3);
		$arr[0] = "D";
		$arr[1] = "V";
		$arr[2] = "R";
		
		return ($arr[rand(0,2)]);
	}
?>